<!doctype html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Альпаки</title>
    </head>
    <body>
        <header>
        <h3><p align="center">Альпаки - это лучшее, что могла придумать природа. Альпака — животные не очень крупные: их рост не превышает одного метра, весят они около 70 кг. Цветовая гамма шерсти альпака очень разнообразна: существует два десятка оттенков - от кипенно-белого до коричневого и даже черного.
        Альпака — это очень застенчивое и очень умное животное, которое не любит проявлять агрессию.</p></h3>
        <hr>
        </header>
        <div>
            <main>
        <h2>Вы можете убедиться в их красоте сами! Просто посмотрите, какие альпаки милашки:</h2>
        <img src="https://cdn.fishki.net/upload/post/2020/07/29/3381103/a59bb53d9c545a7169805ac35ffe91c1.jpg" width="420">
        <p align="right"><img src="https://webpulse.imgsmail.ru/imgpreview?key=pic798150400984397579&mb=pulse" width="420"></p>
        </main>
        <nav>
            <ul>
                <h1><p align="CENTER"><a href=".html">На главную</a></h1></p>
            </ul>
        </nav>
        </div>
    </body>
</html>